[package]
name = "rust-color-visuals"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1"
pixels = "0.12.1"
winit = "0.28"
noise = "0.8"
glam = { version = "0.27", features = ["fast-math"] }
rand = "0.8"
image = { version = "0.24", default-features = false, features = ["png", "ico", "jpeg"] }
windows-sys = { version = "0.52.0", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }
raw-window-handle = "0.5"

[build-dependencies]
toml = "0.8"
